name: PR Pipeline

on:
  pull_request:
    branches:
      - master

jobs:

  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: Install Dependencies
        run: make dev -B

  # ------------------------------------------------------------------------------------------------------------------------

  jest:
    name: Jest Tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: Run Jest
        run: make jest -B

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: Run ESLint
        run: make eslint -B

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: Run Stylelint
        run: make stylelint -B

  # ------------------------------------------------------------------------------------------------------------------------

  php_checks:
    name: PHP Syntax Checks
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: PHP Syntax Checks
        run: make phpcheck -B

  php_min:
    name: PHP 5.6 Compatibility
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: PHP Checks
        run: make phpmin -B

  # ------------------------------------------------------------------------------------------------------------------------

  unit_tests:
    name: Unit Tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: Run PHPUnit
        run: make phpunit -B

  # ------------------------------------------------------------------------------------------------------------------------

  phpstan:
    name: PHPStan Analyser
    needs: install
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: Run PHPStan
        run: make stan -B

  phpcsfixer:
    name: PHP CS Fixer
    needs: install
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            vendor

      - name: Run PHP CS Fixer
        run: make csfix -B

  # ------------------------------------------------------------------------------------------------------------------------

  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Create Cache Directories
        run: |
          mkdir -p ~/.build

      - name: Mount Build Cache
        uses: actions/cache@v3
        with:
          key: cache-plugin-${{ github.run_id }}
          path: ~/.build

      - name: Build Plugin
        uses: ./.github/actions/build-plugin
        with:
          shopware: 5.7.15

  snippets:
    name: Validate Snippet Files
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Build Cache
        uses: actions/cache@v3
        with:
          key: cache-plugin-${{ github.run_id }}
          path: ~/.build

      - name: Snippet Tests
        uses: ./.github/actions/run-snippets
        with:
          SHOPWARE: 5.7.15
          PHP: 7.4

  install_tests:
    name: Install | Shopware ${{ matrix.shopware }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        shopware: [ '5.7.0', '5.6.10', '5.6.9', '5.3.0' ]
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Build Cache
        uses: actions/cache@v3
        with:
          key: cache-plugin-${{ github.run_id }}
          path: ~/.build

      - name: Installation Tests, Shopware ${{ matrix.shopware }}
        uses: ./.github/actions/run-e2e
        with:
          # -------------------------------------------
          SHOPWARE: ${{ matrix.shopware }}
          PHP: 7.4
          # -------------------------------------------
          MOLLIE_APIKEY_TEST: ""
          # -------------------------------------------
          RUN_CYPRESS: false

  e2e:
    name: E2E Core | Shopware ${{ matrix.shopware }}, PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - shopware: '5.7.15'
            php: '8.1'
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Build Cache
        uses: actions/cache@v3
        with:
          key: cache-plugin-${{ github.run_id }}
          path: ~/.build

      - name: E2E Tests, Shopware ${{ matrix.shopware }}
        uses: ./.github/actions/run-e2e
        with:
          # -------------------------------------------
          SHOPWARE: ${{ matrix.shopware }}
          PHP: ${{ matrix.php }}
          # -------------------------------------------
          MOLLIE_APIKEY_TEST: ""
          # -------------------------------------------
          RUN_CYPRESS: true
          TESTRAIL: false
          # only run @core tests, because we have no API key here
          FILTERS: "@core"
